package com.icuscn.passerby.common.model;

import com.icuscn.passerby.common.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	
}
